name: CD

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Simulate deployment
        run: echo "Deploying application..."
      - name: Use secret
        run: echo "The secret is ${{ secrets.DEPLOY_KEY }}"
